name = "MyNine"
uuid = "7cd01866-22fe-4af4-85d0-9956eff2598f"
authors = ["Florian Besten"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
